# save as .github/workflows/dispatch.yml
# run on Terminal: gh workflow run 'dispatch' --ref branch-name -f verbosity=debug -f os=windows
name: dispatch

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating System to run on
        required: false
        default: windows
        type: choice
        options: 
        - ubuntu
        - macos
        - windows
      os_version:
        description: OS version
        required: false
        default: latest
        type: string
      raku_version:
        description: Raku version
        required: false
        default: latest
        type: string
      path_separator:
        description: OS specific path separator
        required: false
        default: '\'
        type: string
      tmp_dir:
        description: OS specific tmp dir
        required: false
        default: 'tmp'
        type: string

jobs:
  launch:
    uses: ./.github/workflows/runner.yml
    with:
      os: ${{ inputs.os }}
      os_version: ${{ inputs.os_version }}
      raku_version: ${{ inputs.raku_version }}
      path_separator: ${{ inputs.path_separator }}
      tmp_dir: ${{ inputs.tmp_dir }}
