# save as .github/workflows/Linux.yml
name: Linux

on: [ push, pull_request ]

jobs:
  launch:
    uses: ./.github/workflows/runner.yml
    with:
      os: ubuntu
      os_version: latest
      raku_version: latest
