# save as .github/workflows/Windows.yml
name: Windows

on: [ push, pull_request ]

jobs:
  launch:
    uses: ./.github/workflows/runner.yml
    with:
      os: ${{ github.workflow }}
      os_version: latest
      raku_version: latest
      path_separator: '\'
      tmp_dir: 'tmp'
