# save as .github/workflows/Windows.yml
name: Windows

on: [ push, pull_request ]

jobs:
  launch:
    uses: ./.github/workflows/runner.yml
    with:
      os: ${{ github.workflow }}
      path_separator: '\'